// automatically generated by the FlatBuffers compiler, do not modify

namespace slyther.flatbuffers
{

public enum ClientMessageType : byte
{
 NONE = 0,
 ClientHello = 1,
 ClientInputState = 2,
 ClientGoodbye = 3,
 TickAck = 4,
};


}
