// automatically generated by the FlatBuffers compiler, do not modify

namespace slyther.flatbuffers
{

public enum NetworkObjectStateType : byte
{
 NONE = 0,
 NetworkFoodState = 1,
 NetworkSnakeState = 2,
};


}
