// automatically generated by the FlatBuffers compiler, do not modify

namespace slyther.flatbuffers
{

using System;
using FlatBuffers;

public sealed class NetworkFoodState : Table {
  public static NetworkFoodState GetRootAsNetworkFoodState(ByteBuffer _bb) { return GetRootAsNetworkFoodState(_bb, new NetworkFoodState()); }
  public static NetworkFoodState GetRootAsNetworkFoodState(ByteBuffer _bb, NetworkFoodState obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public NetworkFoodState __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public slyther.flatbuffers.Vec2 Position { get { return GetPosition(new slyther.flatbuffers.Vec2()); } }
  public slyther.flatbuffers.Vec2 GetPosition(slyther.flatbuffers.Vec2 obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public byte Weight { get { int o = __offset(8); return o != 0 ? bb.Get(o + bb_pos) : (byte)0; } }
  public bool IsActive { get { int o = __offset(10); return o != 0 ? 0!=bb.Get(o + bb_pos) : (bool)false; } }

  public static void StartNetworkFoodState(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<slyther.flatbuffers.Vec2> positionOffset) { builder.AddStruct(1, positionOffset.Value, 0); }
  public static void AddWeight(FlatBufferBuilder builder, byte weight) { builder.AddByte(2, weight, 0); }
  public static void AddIsActive(FlatBufferBuilder builder, bool isActive) { builder.AddBool(3, isActive, false); }
  public static Offset<NetworkFoodState> EndNetworkFoodState(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NetworkFoodState>(o);
  }
};


}
