// automatically generated by the FlatBuffers compiler, do not modify

namespace slyther.flatbuffers
{

public enum NetworkMessageType : byte
{
 NONE = 0,
 ClientMessage = 1,
 ServerMessage = 2,
};


}
