// automatically generated by the FlatBuffers compiler, do not modify

namespace slyther.flatbuffers
{

public enum ServerMessageType : byte
{
 NONE = 0,
 ServerHello = 1,
 ServerWorldState = 2,
 ServerGoodbye = 3,
 TickAck = 4,
};


}
