// automatically generated by the FlatBuffers compiler, do not modify

package in.slyther.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ClientHello extends Table {
  public static ClientHello getRootAsClientHello(ByteBuffer _bb) { return getRootAsClientHello(_bb, new ClientHello()); }
  public static ClientHello getRootAsClientHello(ByteBuffer _bb, ClientHello obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ClientHello __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String playerName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createClientHello(FlatBufferBuilder builder,
      int playerNameOffset) {
    builder.startObject(1);
    ClientHello.addPlayerName(builder, playerNameOffset);
    return ClientHello.endClientHello(builder);
  }

  public static void startClientHello(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPlayerName(FlatBufferBuilder builder, int playerNameOffset) { builder.addOffset(0, playerNameOffset, 0); }
  public static int endClientHello(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

