// automatically generated by the FlatBuffers compiler, do not modify

namespace slyther.flatbuffers
{

using System;
using FlatBuffers;

public sealed class FColor : Struct {
  public FColor __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public uint R { get { return bb.GetUint(bb_pos + 0); } }
  public uint G { get { return bb.GetUint(bb_pos + 4); } }
  public uint B { get { return bb.GetUint(bb_pos + 8); } }

  public static Offset<FColor> CreateFColor(FlatBufferBuilder builder, uint R, uint G, uint B) {
    builder.Prep(4, 12);
    builder.PutUint(B);
    builder.PutUint(G);
    builder.PutUint(R);
    return new Offset<FColor>(builder.Offset);
  }
};


}
