// automatically generated by the FlatBuffers compiler, do not modify

package in.slyther.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NetworkMessage extends Table {
  public static NetworkMessage getRootAsNetworkMessage(ByteBuffer _bb) { return getRootAsNetworkMessage(_bb, new NetworkMessage()); }
  public static NetworkMessage getRootAsNetworkMessage(ByteBuffer _bb, NetworkMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public NetworkMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long id() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public byte msgType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table msg(Table obj) { int o = __offset(8); return o != 0 ? __union(obj, o) : null; }

  public static int createNetworkMessage(FlatBufferBuilder builder,
      long id,
      byte msg_type,
      int msgOffset) {
    builder.startObject(3);
    NetworkMessage.addMsg(builder, msgOffset);
    NetworkMessage.addId(builder, id);
    NetworkMessage.addMsgType(builder, msg_type);
    return NetworkMessage.endNetworkMessage(builder);
  }

  public static void startNetworkMessage(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addInt(0, (int)id, 0); }
  public static void addMsgType(FlatBufferBuilder builder, byte msgType) { builder.addByte(1, msgType, 0); }
  public static void addMsg(FlatBufferBuilder builder, int msgOffset) { builder.addOffset(2, msgOffset, 0); }
  public static int endNetworkMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishNetworkMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

