// automatically generated by the FlatBuffers compiler, do not modify

package in.slyther.flatbuffers;

public final class NetworkMessageType {
  private NetworkMessageType() { }
  public static final byte NONE = 0;
  public static final byte ClientMessage = 1;
  public static final byte ServerMessage = 2;

  public static final String[] names = { "NONE", "ClientMessage", "ServerMessage", };

  public static String name(int e) { return names[e]; }
}

