// automatically generated by the FlatBuffers compiler, do not modify

package slyther.flatbuffers;

public final class ClientMessageType {
  private ClientMessageType() { }
  public static final byte NONE = 0;
  public static final byte ClientHello = 1;
  public static final byte ClientInputState = 2;
  public static final byte ClientGoodbye = 3;
  public static final byte TickAck = 4;

  public static final String[] names = { "NONE", "ClientHello", "ClientInputState", "ClientGoodbye", "TickAck", };

  public static String name(int e) { return names[e]; }
}

