// automatically generated by the FlatBuffers compiler, do not modify

package slyther.flatbuffers;

public final class NetworkObjectStateType {
  private NetworkObjectStateType() { }
  public static final byte NONE = 0;
  public static final byte NetworkFoodState = 1;
  public static final byte NetworkSnakeState = 2;

  public static final String[] names = { "NONE", "NetworkFoodState", "NetworkSnakeState", };

  public static String name(int e) { return names[e]; }
}

