// automatically generated by the FlatBuffers compiler, do not modify

package slyther.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ServerMessage extends Table {
  public static ServerMessage getRootAsServerMessage(ByteBuffer _bb) { return getRootAsServerMessage(_bb, new ServerMessage()); }
  public static ServerMessage getRootAsServerMessage(ByteBuffer _bb, ServerMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ServerMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte msgType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table msg(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createServerMessage(FlatBufferBuilder builder,
      byte msg_type,
      int msgOffset) {
    builder.startObject(2);
    ServerMessage.addMsg(builder, msgOffset);
    ServerMessage.addMsgType(builder, msg_type);
    return ServerMessage.endServerMessage(builder);
  }

  public static void startServerMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMsgType(FlatBufferBuilder builder, byte msgType) { builder.addByte(0, msgType, 0); }
  public static void addMsg(FlatBufferBuilder builder, int msgOffset) { builder.addOffset(1, msgOffset, 0); }
  public static int endServerMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishServerMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

