// automatically generated by the FlatBuffers compiler, do not modify

package slyther.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ServerGoodbye extends Table {
  public static ServerGoodbye getRootAsServerGoodbye(ByteBuffer _bb) { return getRootAsServerGoodbye(_bb, new ServerGoodbye()); }
  public static ServerGoodbye getRootAsServerGoodbye(ByteBuffer _bb, ServerGoodbye obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ServerGoodbye __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startServerGoodbye(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endServerGoodbye(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

